apiVersion: apps/v1
kind: Deployment
metadata:
  name: mookube
  labels:
    app: mookube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mookube
  template:
    metadata:
      labels:
        app: mookube
    spec:
      containers:
      - name: mookube
        image: ${{DOCKER_REGISTRY}}/mookube:latest
        ports:
        - containerPort: 4499
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 4499
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 4499
          initialDelaySeconds: 5
          periodSeconds: 5